In [8]:
import numpy as np

In [1]:
a= [1,2,3,4,5]


In [2]:
print(a)

[1, 2, 3, 4, 5]


In [3]:
print(type(a))

<class 'list'>


In [12]:
L = range(1000)
%timeit  [i**2 for i in L]

125 µs ± 3.68 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [18]:
np_a = np.array(a)

In [19]:
print(np_a)

[1 2 3 4 5]


In [20]:
print (type(np_a))

<class 'numpy.ndarray'>


In [22]:
#1-D
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [23]:
#print dimensions
a.ndim

1

In [24]:
#shape
a.shape

(4,)

In [25]:
# 2-D
b = np.array([[0,1,2], [3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
b.ndim

2

In [27]:
b.shape

(2, 3)

In [28]:
#3D
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
c.ndim

3

In [30]:
c.shape

(2, 2, 2)

In [31]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [32]:
np.array(my_list)

array([1, 2, 3])

In [33]:
np.array(my_list)

array([1, 2, 3])

In [34]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [35]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.array(my_matrix).shape

(3, 3)

In [37]:
a = np.linspace (0, 5, 6)
a

array([0., 1., 2., 3., 4., 5.])

In [39]:
np.zeros(3)

array([0., 0., 0.])

In [41]:
b = np.zeros(3)

In [42]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [43]:
a = np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
d = np.eye(3,2)
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [47]:
a = np.diag([7,9,3,4])
a

array([[7, 0, 0, 0],
       [0, 9, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [48]:
np.diag(a)

array([7, 9, 3, 4])

In [49]:
random_array =  np.random.randint(1,121,5)
print(random_array)

[106  61  51  73 113]


In [50]:
a = np. random.rand(4)
a
                    

array([0.77235987, 0.39008987, 0.73968595, 0.67345594])

In [51]:
a = np.random.randn(100)
a

array([ 0.09274091,  0.31867661, -0.24229404, -1.68582339,  0.49798996,
       -0.18338987,  0.64472073, -0.22742969,  1.1306274 ,  0.48438254,
        2.2079065 , -1.15359444, -0.42201581, -0.6788031 , -1.89889761,
       -0.77052189,  0.31522774,  0.24012462,  1.59031699,  0.21583726,
        0.47547943, -0.0235229 , -0.40462822, -0.40553083,  0.52115888,
        1.07643016,  1.14740569, -0.04690218, -0.59225095,  0.22597913,
        0.78902422,  0.65203202, -1.47858191, -0.56492061,  0.44807392,
        0.57942634,  0.71058005, -0.40792423,  0.80122548,  1.15138048,
        0.37397077, -0.66817684, -0.36823662,  1.31981698, -0.14838495,
       -0.21880168, -1.20122123,  0.65582043, -1.23914815, -0.5893473 ,
       -0.2545683 ,  0.73694519,  0.80708532,  0.9084263 , -0.18455201,
       -0.35963915, -0.10207058, -0.76813393,  1.45474028, -1.01384406,
        1.79381853, -1.35641839,  0.29613038,  0.02092975,  0.02088167,
       -2.58370697,  0.03266329,  1.80624472, -0.89038902, -0.33

In [52]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [54]:
arr = np.arange(25)
print(arr)
print(arr.shape)
                 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [55]:
a1=arr.reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print("shape of a: {}".format(a.shape))

[[1 2 3]
 [4 5 6]]
shape of a: (2, 3)


In [57]:
b = a.reshape(3,2)
print(b)
print("shape of b: {}".format(b.shape))

[[1 2]
 [3 4]
 [5 6]]
shape of b: (3, 2)


In [58]:
a = np.array([[1,2,3], [4,5,6]])
print("shape: {}",format(a.shape))
print(a)

shape: {} (2, 3)
[[1 2 3]
 [4 5 6]]


In [59]:
c = a.T
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [60]:
a = np.array([[5,4,6], [2,8,2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 8]])

In [63]:
a =  np.array([4, 7, 8])
a = np.append(a, [2,4,5])
print('Numpy array after addition:',a)

Numpy array after addition: [4 7 8 2 4 5]


In [65]:
a = np.delete(a,2)
print('Numpy array after deletion of one element:',a)

Numpy array after deletion of one element: [4 7 2 4 5]


In [69]:
a = np.arange(3,10)
print(a)
print(a[5])


[3 4 5 6 7 8 9]
8


In [70]:
a = np.diag([1,2,3])
print(a)
print(a[2,1])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
0


In [71]:
a[2,1] = 5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [73]:
a = np.arange(4,18)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [12]:
df = pd.read_csv(r"C:\Users\Poonam\Downloads\archive\Tesla.csv - Tesla.csv.csv")
df.describe(include="all")
df.info

<bound method DataFrame.info of            Date        Open        High         Low       Close    Volume  \
0     6/29/2010   19.000000   25.000000   17.540001   23.889999  18766300   
1     6/30/2010   25.790001   30.420000   23.299999   23.830000  17187100   
2      7/1/2010   25.000000   25.920000   20.270000   21.959999   8218800   
3      7/2/2010   23.000000   23.100000   18.709999   19.200001   5139800   
4      7/6/2010   20.000000   20.000000   15.830000   16.110001   6866900   
...         ...         ...         ...         ...         ...       ...   
1687  3/13/2017  244.820007  246.850006  242.779999  246.169998   3010700   
1688  3/14/2017  246.110001  258.119995  246.020004  258.000000   7575500   
1689  3/15/2017  257.000000  261.000000  254.270004  255.729996   4816600   
1690  3/16/2017  262.399994  265.750000  259.059998  262.049988   7100400   
1691  3/17/2017  264.000000  265.329987  261.200012  261.500000   6475900   

       Adj Close  
0      23.889999  
1    

In [9]:
a = np.array([1, 2, 3, 4,])
b  = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [10]:
a > b

array([False, False,  True, False])

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.array([1, 2, 3, 4])

In [12]:
np.array_equal(a,b)

False

In [13]:
np.array_equal(a, c)

True

In [15]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [16]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [17]:
np. log(a)

C:\Users\Poonam\AppData\Local\Temp\ipykernel_20168\910223754.py:1: RuntimeWarning: divide by zero encountered in log
  np. log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [18]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [19]:
a = np.arrange(4)
a + np.array([1, 2])

AttributeError: module 'numpy' has no attribute 'arrange'

In [20]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [21]:
x = np.array([[1, 1],[2, 2]])
x

array([[1, 1],
       [2, 2]])

In [22]:
x.sum(axis=1)

array([2, 4])

In [23]:
x = np.array([1, 3, 2])
x.min()

1

In [24]:
x. max()

3

In [25]:
x.argmin()

0

In [26]:
x.argmax()

1

In [27]:
normal_array = np.arange(0,10,1)
print('Array is ',format(normal_array))

### Min
print('min element is', np.min(normal_array))

### Max
print('max element is', np.max(normal_array))

### Sum
print('sum of element in array is ',np.sum(normal_array))

### Mean
print('mean of element in array is ',np.mean(normal_array))

### Median
print('median of element in array is ',np.median(normal_array))

### Sd
print('standard deviation of elements in array is ',np.std(normal_array))

Array is  [0 1 2 3 4 5 6 7 8 9]
min element is 0
max element is 9
sum of element in array is  45
mean of element in array is  4.5
median of element in array is  4.5
standard deviation of elements in array is  2.8722813232690143


In [28]:
a = np.ones(4) +1 
b

array([ True, False,  True, False])

In [29]:
a - b

array([1., 2., 1., 2.])

In [30]:
a * b

array([2., 0., 2., 0.])

In [ ]:
a = np. array([[1,2],[3,4] [5, 6]
b = np.array(4,4) [4,4]
        